runtime: java21

instance_class: F1

default_expiration: 5m

automatic_scaling:
  min_instances: 1
  max_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /static
    static_dir: static

  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /$
    static_files: static/index.html
    upload: static/index.html

  - url: /.*
    script: auto

# env_variables:
#  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=240m -Xmx56m"
# entrypoint: ./gaeserver