// source: audio.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.micromova.proto.Format', null, global);
goog.exportSymbol('proto.micromova.proto.Recording', null, global);
goog.exportSymbol('proto.micromova.proto.Type', null, global);
goog.exportSymbol('proto.micromova.proto.VoiceGender', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.micromova.proto.Recording = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.micromova.proto.Recording, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.micromova.proto.Recording.displayName = 'proto.micromova.proto.Recording';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.micromova.proto.Recording.prototype.toObject = function(opt_includeInstance) {
  return proto.micromova.proto.Recording.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.micromova.proto.Recording} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micromova.proto.Recording.toObject = function(includeInstance, msg) {
  var f, obj = {
    voiceGender: jspb.Message.getFieldWithDefault(msg, 1, 0),
    format: jspb.Message.getFieldWithDefault(msg, 2, 0),
    uri: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.micromova.proto.Recording}
 */
proto.micromova.proto.Recording.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.micromova.proto.Recording;
  return proto.micromova.proto.Recording.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.micromova.proto.Recording} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.micromova.proto.Recording}
 */
proto.micromova.proto.Recording.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.micromova.proto.VoiceGender} */ (reader.readEnum());
      msg.setVoiceGender(value);
      break;
    case 2:
      var value = /** @type {!proto.micromova.proto.Format} */ (reader.readEnum());
      msg.setFormat(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 4:
      var value = /** @type {!proto.micromova.proto.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.micromova.proto.Recording.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.micromova.proto.Recording.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.micromova.proto.Recording} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.micromova.proto.Recording.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVoiceGender();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getFormat();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional VoiceGender voice_gender = 1;
 * @return {!proto.micromova.proto.VoiceGender}
 */
proto.micromova.proto.Recording.prototype.getVoiceGender = function() {
  return /** @type {!proto.micromova.proto.VoiceGender} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.micromova.proto.VoiceGender} value
 * @return {!proto.micromova.proto.Recording} returns this
 */
proto.micromova.proto.Recording.prototype.setVoiceGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Format format = 2;
 * @return {!proto.micromova.proto.Format}
 */
proto.micromova.proto.Recording.prototype.getFormat = function() {
  return /** @type {!proto.micromova.proto.Format} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.micromova.proto.Format} value
 * @return {!proto.micromova.proto.Recording} returns this
 */
proto.micromova.proto.Recording.prototype.setFormat = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string uri = 3;
 * @return {string}
 */
proto.micromova.proto.Recording.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.micromova.proto.Recording} returns this
 */
proto.micromova.proto.Recording.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Type type = 4;
 * @return {!proto.micromova.proto.Type}
 */
proto.micromova.proto.Recording.prototype.getType = function() {
  return /** @type {!proto.micromova.proto.Type} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.micromova.proto.Type} value
 * @return {!proto.micromova.proto.Recording} returns this
 */
proto.micromova.proto.Recording.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.micromova.proto.VoiceGender = {
  UNKNOWN_GENDER: 0,
  FEMALE: 1,
  MALE: 2
};

/**
 * @enum {number}
 */
proto.micromova.proto.Format = {
  UNKNOWN_FORMAT: 0,
  MP3: 1
};

/**
 * @enum {number}
 */
proto.micromova.proto.Type = {
  UNKNOWN_TYPE: 0,
  GOOGLE_TEXT_TO_SPEECH: 1
};

goog.object.extend(exports, proto.micromova.proto);
